name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Download Gradle
        run: |
          wget https://services.gradle.org/distributions/gradle-8.5-bin.zip
          unzip -q gradle-8.5-bin.zip
          echo "$PWD/gradle-8.5/bin" >> $GITHUB_PATH

      - name: Build with Gradle
        run: gradle assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: VCamSX-APK
          path: app/build/outputs/apk/release/*.apk
